generatorName: kotlin-spring
outputDir: samples/server/petstore/kotlin-springboot-request-cookie
library: spring-boot
inputSpec: modules/openapi-generator/src/test/resources/3_0/kotlin/petstore-with-fake-endpoints-with-cookie-parameters.yaml
templateDir: modules/openapi-generator/src/main/resources/kotlin-spring
additionalProperties:
  appendRequestToHandler: true
  interfaceOnly: true
  useSpringBoot3: true
